services:

  nginx:
    build: nginx
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - app
    networks:
      - frontnet
    volumes:
      - /Users/amirhossein/Desktop/shared:/shared

  app:
    build: app
    restart: always
    ports:
      - 3001:3001
    networks:
      - frontnet


networks:
  frontnet: